### PR TITLE
make tab actually 2 spaces

### PR DESCRIPTION
**Pull request by ryanpcmcquen**
Worthy reading: http://tedlogan.com/techblog3.html

### CODE REVIEW

**Comment by ssorallen** [comment]
Nice, I dig it. Thanks for the fix.

**Comment by ryanpcmcquen** [comment]
Just found it today! :+1:

**Comment by ryanpcmcquen** [comment]
@ssorallen, note that if you ever need the `set paste` functionality in vim, you can just include this plugin in your `$HOME/.vimrc`:

https://github.com/ConradIrwin/vim-bracketed-paste

I don't actually install plugins, so I just dropped the code from there into my `.vimrc`:

https://github.com/ryanpcmcquen/linuxTweaks/blob/master/.vimrc#L78-L130

**Comment by ryanpcmcquen** [comment]
The reason I mention this is that `set paste` destroys your indentation settings. :wink:

**Pull request merged**
